### ISSUE TITLE
Subscribing to more than 100 streams silently fails

### ISSUE THREAD

**Issue by hg-jarlinghaus** [EventStore/EventStore-Client-NodeJS#175]
After calling subscribeToStream 100 times any new calls to subscribeToStream will no longer receive any data, and will not issue any error. Weirdly enough this persists even across multiple connections, so creating two connections to the database and having the first connection subscribe 50 times to a stream and the second connection subscribe 51 times, the 101st subscription created across the whole process will not receive any data. This does not appear to be a server limit however, because running two processes that call subscribeToStream 90 times each will all receive data just fine.

**Comment by hayley-jean** [comment]
Hi @hg-jarlinghaus, thanks for reporting this!
Do you see any errors on the server when you create the final subscription?

What is your use-case for running so many subscriptions from the same process?
And would you mind sharing it in [Discuss](https://discuss.eventstore.com/) so that our dev advocacy team can better understand your use, and offer guidance if needed?

**Comment by w1am** [comment]
This issue has been inactive for a while, so we’ll close it for now. Feel free to reopen or create a new issue if needed.
