### ISSUE TITLE
Trouble connecting to cloud cluster from AWS

### ISSUE THREAD

**Issue by samhatoum** [EventStore/EventStore-Client-NodeJS#322]
I have setup a cloud cluster on eventstore.com, and I have setup a VPC with 2 private subnets that have routes to the eventstore network. I've verified that I have a connection from my Node.js Lambda function that's inside the VPC to the EventStore by running a fetch to UI, and I can see the response the correct html response:

```
<!DOCTYPE html>...<script data-main=js/app.min.js src=js/requirejs.min.js>...
```
So I'm (mostly) sure I've got the networking part figured out.

However, when I try to create a connection using:
```
EventStoreDBClient.connectionString`esdb://XXXXXX.mesdb.eventstore.cloud:2113`
```
I get `7 PERMISSION_DENIED: Access Denied`

and when I try using:
```
EventStoreDBClient.connectionString`esdb://XXXXXX.mesdb.eventstore.cloud:2113?tls=false`
```
I get: `14 UNAVAILABLE: Connection dropped`

What's the correct way to connect? How does one set credentials for the cloud instance?

**Comment by George-Payne** [comment]
Hi Sam,

> `7 PERMISSION_DENIED: Access Denied`

Looks like you are connecting correctly, but are trying to access something that requires credentials.

You can set the default credentials on your connection string:

```js
EventStoreDBClient.connectionString`esdb://username:password@XXXXXX.mesdb.eventstore.cloud:2113`
```
And override them on a call by call basis (every call takes credentials in it's final options argument):

```js
const result = await client.appendToStream(STREAM_NAME, event, {
  credentials: { username: "username", password: "password" },
});
```

It's better to set the default in the connection string as it allows the client to apply optimisations like appending events over a single long running connection, which per call credentials don't allow.

---

The default admin database credentials are: 
- Username: `admin` 
- Password: `changeit`

Which you should change to something more secure. This can be done via the database UI  (click on `users` -> `admin` -> `password reset`) or over http: https://developers.eventstore.com/clients/http-api/v5/api.html#change-password

---

If it turns out this isn't the issue, can you enable debug logs and send the output:

```
DEBUG="esdb:*" node main.js
```

---

George

**Comment by samhatoum** [comment]
Thank you so much, that did the trick
